services:
  postgres:
    image: postgres:17-alpine
    container_name: trm_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./infra/postgres_data:/var/lib/postgresql/data:Z
    networks:
      - trm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: trm_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./infra/redis_data:/data:Z
    networks:
      - trm_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  trm_network:
    driver: bridge
